name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Prepare
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y --no-install-recommends ca-certificates curl gnupg openssl
          curl -L 'https://dl.winehq.org/wine-builds/winehq.key' | apt-key add -
          echo 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main' > /etc/apt/sources.list.d/winehq.list
          dpkg --add-architecture i386
          apt-get update
          apt-get install -y --no-install-recommends git gcc g++ meson ninja-build wine-devel-dev winehq-devel
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: meson setup ./build --cross-file ./build-wine64.txt --libdir lib --prefix /usr --buildtype release --strip
      - name: Build
        run: ninja -C ./build
      - name: Install
        run: env DESTDIR="${PWD}" ninja -C ./build install
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wine-nvoptix
          # TODO: fix defs and fakedlls being installed to weird locations
          path: usr/lib/**