name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Prepare
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update && apt-get -y upgrade
          apt-get install -y --no-install-recommends meson ninja-build wine64-tools
          echo "/usr/lib/wine" >> $GITHUB_PATH
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: meson setup ./build --cross-file ./build-wine64.txt --libdir lib --prefix /usr --buildtype release --strip
      - name: Build
        run: ninja -C ./build
      - name: Install
        run: env DESTDIR="${PWD}" ninja -C ./build install
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wine-nvoptix
          # TODO: fix defs and fakedlls being installed to weird locations
          path: usr/lib/**
